- platform: snmp
  name: "Homelab Server PDU Load"
  host: !secret snmp_pdu_host
  accept_errors: true
  community: !secret snmp_community
  baseoid: .1.3.6.1.4.1.3808.1.1.3.2.3.1.1.2.1
  unit_of_measurement: A
  value_template: "{{((value | float) / 10) | float}}"

# https://seveas.github.io/python-hpilo/health.html
- platform: hp_ilo
  host: !secret hp_server_ilo_ipaddress
  username: !secret hp_server_ilo_username
  password: !secret hp_server_ilo_password
  #scan_interval: 30
  monitored_variables:
    - name: health_bios_hardware
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['bios_hardware']['status'] }}"
    - name: health_fan_status
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['fans']['status'] }}"
    - name: health_memory_status
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['memory']['status'] }}"
    - name: health_network_status
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['network']['status'] }}"
    - name: health_processor_status
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['processor']['status'] }}"
    - name: health_storage_status
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['storage']['status'] }}"
    - name: health_temperature_status
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance['temperature']['status'] }}"
    - name: server_name
      sensor_type: server_name
    - name: power_status
      sensor_type: server_power_status
    - name: power_reading
      sensor_type: server_health
      value_template: "{{ ilo_data.power_supply_summary['present_power_reading'] }}"
    - name: power_on_time
      sensor_type: server_power_on_time
    - name: uid_status
      sensor_type: server_uid_status      
    - name: temp_inlet
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
    - name: temp_cpu1
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: '{{ ilo_data.temperature["02-CPU 1"].currentreading[0] }}'
    - name: temp_cpu2
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: '{{ ilo_data.temperature["03-CPU 2"].currentreading[0] }}'

- !include sensors/datetime_sensors.yaml
# !include sensors/hvac_sensors.yaml
# !include sensors/system_sensors.yaml
# !include sensors/xfinity_sensors.yaml


