homeassistant:
  
  customize_glob:
    "binary_sensor.*door":
      device_class: door
    "binary_sensor.*window":
      device_class: window
    "binary_sensor.*window_left":
      device_class: window
    "binary_sensor.*window_right":
      device_class: window
    "binary_sensor.*window_left_small":
      device_class: window
    "binary_sensor.*window_right_small":
      device_class: window
    "binary_sensor.*window_front":
      device_class: window
    "binary_sensor.*window_peep":
      device_class: window
    "binary_sensor.*motion":
      device_class: motion
    "switch.*light_fan":
      icon: mdi:ceiling-fan-light
    

# Enables configuration UI
config:
my:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation: 

device_tracker:

# Discover some devices automatically
energy:
hassio:

ios:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

frontend: !include frontend.yaml
sensor: !include cfg_sensor.yaml
binary_sensor: !include cfg_binary_sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  listen_port: !secret emulated_hue_listen_port
  expose_by_default: false
  entities:
    light.living_room_light:
      hidden: false
    fan.master_bedroom_fan:
      hidden: false
    switch.kitchen_light:
      hidden: false
    switch.entryway_light:
      hidden: false
    switch.entryway_outlet_switch:
      hidden: false
    switch.welcome_room_light:
      hidden: false
    switch.backyard_light_left:
      hidden: false
    switch.backyard_light_right:
      hidden: false
    switch.side_deck_light:
      hidden: false
    switch.upper_guest_bedroom_light_fan:
      hidden: false
    switch.upper_small_bedroom_light_fan:
      hidden: false
    switch.home_theatre_living_room:
      hidden: false
    switch.backyard_mesh_lights:
      hidden: false
    switch.backyard_gym_lights:
      hidden: false


geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_week_significant_earthquakes'

history:
  include: !include entity_tracking.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.86.11
    - 192.168.86.0/24
    - 127.0.0.1
    - ::1

influxdb:
  api_version: !secret influxdb_api_version
  ssl: !secret influxdb_ssl
  host: !secret influxdb_host
  port: !secret influxdb_port
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: state
  include: !include entity_tracking.yaml

input_boolean:
  buzz_home:
    name: 'Buzz Home'
    initial: off
    icon: mdi:bullhorn-outline
  reset_internet:
    name: 'Reset Internet'
    initial: off
    icon: mdi:wifi-star

#logbook:
#  include: !include entity_tracking.yaml

#logger:
#  default: info
#  logs:
#    homeassistant.components.camera: info
#    homeassistant.components.zwave: info
#    homeassistant.components.appdaemon: info

lovelace:
  mode: yaml
  resources:
  - url: /hacsfiles/atomic_calendar/atomic_calendar.js
    type: module
  #- url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
  #  type: module
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
  - url: /hacsfiles/bignumber-card/bignumber-card.js
    type: module
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /local/floorplan/floorplan-card.js?v=1.1.14
    type: module

media_source:
media_player:

mobile_app:

notify:

recorder:
  purge_keep_days: 7
  include: !include entity_tracking.yaml

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

system_health:

# tts:
#   - platform: google_translate
    # base_url: !secret home_external_url

#upnp:
#  port_mapping: false
#  sensors: false

wake_on_lan:

zone: !include cfg_zone.yaml
