title: Home
background: var(--background-image)
views:
  - !include lovelace/monitor/main.yaml
  - !include lovelace/thermostats.yaml
  - !include lovelace/lights_fans.yaml
  - !include lovelace/doors_windows.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/alexa.yaml
  - !include lovelace/floorplan.yaml
  - !include lovelace/home.yaml
  - !include lovelace/monitor.yaml
  - !include lovelace/links.yaml

